# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63u.proto\x12\x0cjarvis.cu.v1\x1a\x0c\x63ommon.proto\" \n\x0bPingRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"I\n\x0cPingResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.jarvis.common.v1.Status\x12\x0f\n\x07version\x18\x02 \x01(\t2J\n\tCuService\x12=\n\x04Ping\x12\x19.jarvis.cu.v1.PingRequest\x1a\x1a.jarvis.cu.v1.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=40
  _globals['_PINGREQUEST']._serialized_end=72
  _globals['_PINGRESPONSE']._serialized_start=74
  _globals['_PINGRESPONSE']._serialized_end=147
  _globals['_CUSERVICE']._serialized_start=149
  _globals['_CUSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
