# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\rjarvis.llm.v1\x1a\x0c\x63ommon.proto\" \n\x0bPingRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"I\n\x0cPingResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.jarvis.common.v1.Status\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x8b\x01\n\x0f\x43ompleteRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12*\n\x06intent\x18\x02 \x01(\x0e\x32\x1a.jarvis.llm.v1.IntentClass\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x15\n\rsystem_prompt\x18\x04 \x01(\t\x12\x11\n\tclient_id\x18\x05 \x01(\t\"\xc2\x01\n\x10\x43ompleteResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.jarvis.common.v1.Status\x12\x0c\n\x04text\x18\x02 \x01(\t\x12*\n\x06target\x18\x03 \x01(\x0e\x32\x1a.jarvis.llm.v1.RouteTarget\x12\r\n\x05model\x18\x04 \x01(\t\x12\x14\n\x0cinput_tokens\x18\x05 \x01(\x05\x12\x15\n\routput_tokens\x18\x06 \x01(\x05\x12\x0e\n\x06reason\x18\x07 \x01(\t*\x8d\x01\n\x0bIntentClass\x12\x16\n\x12INTENT_UNSPECIFIED\x10\x00\x12\x11\n\rINTENT_SIMPLE\x10\x01\x12\x19\n\x15INTENT_CONVERSATIONAL\x10\x02\x12\x12\n\x0eINTENT_COMPLEX\x10\x03\x12\x0f\n\x0bINTENT_CODE\x10\x04\x12\x13\n\x0fINTENT_TOOL_USE\x10\x05*I\n\x0bRouteTarget\x12\x16\n\x12TARGET_UNSPECIFIED\x10\x00\x12\x10\n\x0cTARGET_LOCAL\x10\x01\x12\x10\n\x0cTARGET_CLOUD\x10\x02\x32\x9a\x01\n\nLlmService\x12?\n\x04Ping\x12\x1a.jarvis.llm.v1.PingRequest\x1a\x1b.jarvis.llm.v1.PingResponse\x12K\n\x08\x43omplete\x12\x1e.jarvis.llm.v1.CompleteRequest\x1a\x1f.jarvis.llm.v1.CompleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTCLASS']._serialized_start=491
  _globals['_INTENTCLASS']._serialized_end=632
  _globals['_ROUTETARGET']._serialized_start=634
  _globals['_ROUTETARGET']._serialized_end=707
  _globals['_PINGREQUEST']._serialized_start=42
  _globals['_PINGREQUEST']._serialized_end=74
  _globals['_PINGRESPONSE']._serialized_start=76
  _globals['_PINGRESPONSE']._serialized_end=149
  _globals['_COMPLETEREQUEST']._serialized_start=152
  _globals['_COMPLETEREQUEST']._serialized_end=291
  _globals['_COMPLETERESPONSE']._serialized_start=294
  _globals['_COMPLETERESPONSE']._serialized_end=488
  _globals['_LLMSERVICE']._serialized_start=710
  _globals['_LLMSERVICE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
